- name: Push generated pdf to the website repository
  uses: nkoppel/push-files-to-another-repository@1.1.0
  env:
    API_TOKEN_GITHUB: ${{ secrets.SAVE_TO_WEBSITE }}
  with:
    source-files: 'curriculumvitae.pdf'
    destination-username: 'miklere'
    destination-repository: 'miklere.github.io'
    destination-directory: 'projects/website/src'
    commit-email: 'simonindan@gmail.com'