name: Copy generated pdf to the website repository

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy generated pdf to the website repository
        uses: nkoppel/copy-files-to-another-repository@1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.SAVE_TO_WEBSITE }}
        with:
          source-files: 'curriculumvitae.pdf'
          destination-username: 'miklere'
          destination-repository: 'miklere.github.io'
          destination-directory: 'projects/website/src'
          commit-email: 'simonindan@gmail.com'