name: Copy generated pdf to the website repository

on: [push]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy generated pdf to the website repository
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'curriculumvitae.pdf'
          destination-username: 'MikleRe'
          destination-repository: 'website'
          destination-branch: 'main'
          destination-directory: 'src'
          commit-email: 'simonindan@gmail.com'
          commit-message: '[+] Updated curriculum vitae'